### PR TITLE
Add Setup CI for Submerged

### PR DESCRIPTION
**Pull request by GameTechGuides**
hi @Alexejhero ,

Related to #149

 this pr Implements CI workflow and adds build data file as specified.
- Adds a new GitHub Actions workflow file `ci.yml` to automate the build process, including steps for restoring NuGet packages, building the mod in both debug and release configurations, and uploading the resulting DLLs as artifacts.
- Introduces a `build_data.json` file containing the specified JSON structure for build path and dependencies, including download links and paths for BepInEx and Reactor dependencies.

---
if there any thing to change or something else feel free to ask me to do it

### CODE REVIEW

**Comment by Alexejhero** [comment]
Thank you so much for the contribution! I'll take a look at this sometime next week. Please remind me if zi don't.

**Comment by GameTechGuides** [comment]
> Thank you so much for the contribution! I'll take a look at this sometime next week. Please remind me if zi don't.

no problem man i really love the project so much

**Comment by GameTechGuides** [comment]
and a lot of contribution is coming soon

**Review by Alexejhero — CHANGES_REQUESTED** [review]
This pull request is not finished yet, automating release artifacts hasn't been implemented. I won't be merging this in until that is added.

**Comment by GameTechGuides** [comment]
> This pull request is not finished yet, automating release artifacts hasn't been implemented. I won't be merging this in until that is added.

ok i will do that

**Comment by GameTechGuides** [comment]
i have added `automating release artifacts` but i have a problem in the phase of dotnet build it give 859 error i checked the project is restored if u a know a fix tell me

**Review by Alexejhero — CHANGES_REQUESTED** [review]
I'm sorry, the CI should work as described [here](https://github.com/SubmergedAmongUs/Submerged/issues/149#issuecomment-2056557326). This is different.

**Comment by Alexejhero** [comment]
> i have added `automating release artifacts` but i have a problem in the phase of dotnet build it give 859 error i checked the project is restored if u a know a fix tell me

That's a good point, I guess CI is not possible without adding secrets due to #141. I think I'd wait for #141 to be resolved before adding CI.

**Comment by GameTechGuides** [comment]
> > i have added `automating release artifacts` but i have a problem in the phase of dotnet build it give 859 error i checked the project is restored if u a know a fix tell me
> 
> That's a good point, I guess CI is not possible without adding secrets due to #141. I think I'd wait for #141 to be resolved before adding CI.

ok then when the #141 is fixed tell me to fix the ci

**Comment by Alexejhero** [comment]
Closing this for now, #141 has a very low chance of being resolved in the near future

**Pull request closed without merging**
